### ISSUE TITLE
having only 2 bots crashes the game in rare situations

### ISSUE THREAD

**Issue by Heckin-Doggo** [Heckin-Doggo/uno#7]
if you start a game and immediately after set the players to 2, the game crashes for unknown reasons.

**Comment by Heckin-Doggo** [comment]
this has happened now when starting a game with 3 players, leading me to beleive the fact that its only 2 players to be arbitrary

`Traceback (most recent call last):
  File "T:/PycharmProjects/uno-draw-fixing/program.py", line 411, in <module>
    main()
  File "T:/PycharmProjects/uno-draw-fixing/program.py", line 21, in main
    game()
  File "T:/PycharmProjects/uno-draw-fixing/program.py", line 100, in game
    split = discard[-1].find(" ")
AttributeError: 'builtin_function_or_method' object has no attribute 'find'`

**Comment by Heckin-Doggo** [comment]
cannot replicate this bug
